services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=g37_lanches
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack SQS
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./data:/tmp/localstack
