services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=g37_lanches
  localstack:
   image: localstack/localstack
   container_name: localstack
   network_mode: bridge
   ports:
     — "4566:4566"
   volumes:
     — "/var/run/docker.sock:/var/run/docker.sock"