apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: cG9zdGdyZXMK
  POSTGRES_USER: admin
  POSTGRES_PORT: "5432"
  POSTGRES_SSLMODE: disable